---
 - hosts: stadalone
   become: true
#   post_tasks:
#
#     - name: installation complete - create lock file. Needs to works Nginx playbook
#       file: path=/root/wordpress_complete state=file

   roles:
# install some tools
     - misc
# role from ansible galaxy.
#     - role: mrwilson.sqlite 
     - mrwilson.sqlite
# my role
     - nginx
# my role
     - wordpress
     - django

   vars_files:
     - defaults/main.yml
      

