---
- name: ensure port is open in firewall
  firewalld:
    service: mysql
    zone: "{{ item }}"
    permanent: true
    state: enabled
  with_items: mysql_firewall_zones
  when: ansible_distribution == 'Fedora'
