---
- name: ensure upstream repository package is downloaded
  get_url:
    url: http://dev.mysql.com/get/mysql-apt-config_0.6.0-1_all.deb
    dest: /root/mysql-apt-config.deb

- name: ensure upstream repository package is configured
  debconf:
    name: mysql-apt-config
    question: "mysql-apt-config/{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype | default ('select') }}"
  with_items:
    - question: repo-distro
      value: "{{ ansible_distribution | lower }}"
    - question: repo-codename
      value: "{{ ansible_distribution_release }}"
    - question: select-server
      value: "mysql-{{ mysql_upstream_version }}"

# see https://github.com/ansible/ansible-modules-core/pull/2675
- name: check if upstream repository is already installed
  command: dpkg-query -W mysql-apt-config
  register: mysql_apt_config_check_deb
  failed_when: mysql_apt_config_check_deb.rc > 1
  changed_when: mysql_apt_config_check_deb.rc == 1

- name: ensure upstream repository is installed
  apt:
    deb: /root/mysql-apt-config.deb
  register: mysql_upstream_repository_installation
  when: mysql_apt_config_check_deb|changed

- name: ensure apt cache is updated
  apt:
    update_cache: yes
  changed_when: false
  when: mysql_upstream_repository_installation is defined and mysql_upstream_repository_installation|changed

- include: packages.yml
