---
- name: define distribution value for upstream repository
  set_fact:
    mysql_upstream_dist: "{% if ansible_distribution == 'Fedora' %}fc{% else %}el{% endif %}{{ ansible_distribution_version }}"

- name: ensure upstream repository is installed
  package:
    name: "http://dev.mysql.com/get/mysql{{ mysql_upstream_version | replace('.', '') }}-community-release-{{ mysql_upstream_dist }}-7.noarch.rpm"

- include: packages.yml
